version: '3.8'

services:
  app:
    image: smilexah/expense-tracker:latest
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expense_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_APPLICATION_NAME: expense-tracker
      APPLICATION_TITLE: Expense Tracker
      APPLICATION_VERSION: 1.0.0
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8181
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: expense-tracker-db
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
